#!/bin/sh

echo "########## run flake8 ##########"
poetry run flake8
echo "########## run mypy   ##########"
poetry run mypy ./
echo "########## run pytest ##########"
CUDA_VISIBLE_DEVICES='' poetry run pytest
